languageCode = "zh-CN"
languageName = "中文(简体)"
weight = 1
title = "Blog"

[params]
  displayName = "中"
  isoCode = "zh-CN"
  rtl = false
  dateFormat = "2006年1月2日"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "又一个使用Hugo创建的博客"
  copyright = "© 2024 by John Doe, Under CC-BY-NC-SA 4.0"

 [author]
   name = "John Doe"
   image = "img/avatar.png"
   headline = "headline goes here"
   bio = "bio goes here"
   links = [
     { email = "mailto:me@example.com" },
     { link = "https://example.com" },
     { github = "https://github.com" },
     { mastodon = "https://o3o.ca" },
     { steam = "https://steamcommunity.com" },
     { telegram = "https://t.me" },
     { x-twitter = "https://twitter.com" },
     { rocket = "https://www.travellings.cn/go.html"}
   ]
